### PR TITLE
Stream Deck Plus support

### LINKED ISSUE #17: SD+
Any plans to update this for the SD+?

### LINKED ISSUE #21: Needs updating...
This is project still maintained?

It's been a while since it was updated. At least update the references and, for example, the DeviceType enum. As per documentation: Possible values are kESDSDKDeviceType_StreamDeck (0), kESDSDKDeviceType_StreamDeckMini (1), kESDSDKDeviceType_StreamDeckXL (2), kESDSDKDeviceType_StreamDeckMobile (3), kESDSDKDeviceType_CorsairGKeys (4), kESDSDKDeviceType_StreamDeckPedal (5), kESDSDKDeviceType_CorsairVoyager (6), and kESDSDKDeviceType_StreamDeckPlus (7).

Now, it only shows the first 2.

There are some other relatively small changes between the current version (https://developer.elgato.com/documentation/stream-deck/sdk/overview/) and what is in the library.

### PR DESCRIPTION
**Pull request by BarRaider**
1. Support `SystemDidWakeUp` event
2. Support SD+ Events (`DialRotate`, `DialPress`, `TouchPadPress`)
3. Support `SetFeedback` request
4. Support `SetFeedbackLayout` request
5. Add missing DeviceTypes. Note: `StreamDeck` is now renamed to `StreamDeckClassic`

### CODE REVIEW

**Comment by BarRaider** [comment]
Fixes #17 
Fixes #21

**Comment by BarRaider** [comment]
@TyrenDe requires your approval

**Comment by MajMcCloud** [comment]
@TyrenDe Hey! Can you confirm this PR ? 
Thank you

**Comment by TyrenDe** [comment]
Ooh man! So sorry! I wasn't watch this repo.  @BarRaider  - Next time, ping me on discord or something? 😨

**Review by TyrenDe — APPROVED** [review]

**Pull request merged**
